security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${DOCKER_IP:192.168.99.100}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 26000

server:
  context-path: /accounts
  port: 6000

---
spring:
  profiles: docker
  data:
    mongodb:
      host: account-mongodb
      port: 27017
security:
  oauth2:
    client:
      clientId: account-service
