spring:
  data:
    mongodb:
      host: 192.168.99.101
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 25000

server:
  context-path: /uaa
  port: 5000

---
spring:
  profiles: docker
  data:
    mongodb:
      host: auth-mongodb
      port: 27017