security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 192.168.99.101
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27000

server:
  context-path: /statistics
  port: 7000

rates:
  url: http://api.fixer.io

---
spring:
  profiles: docker
  data:
    mongodb:
      host: statistics-mongodb
      port: 27017

security:
  oauth2:
    client:
      accessTokenUri: http://auth-service:5000/uaa/oauth/token